### ISSUE TITLE
How to set model to serve ?

### ISSUE THREAD

**Issue by LarsAC** [otwld/ollama-helm#6]
Hello,

I cannot find how to set the model to serve (e.g. mistral tinyllama) - I would have expected a setting in values.yaml.

The ollama docker container docs instruct to run a separate command via `docker exec` - can this be integrated into the chart directly ?

Lars

**Comment by jdetroyes** [comment]
Hello,

In order to serve a model and chat with it you need to use the ollama  [REST API](https://github.com/jmorganca/ollama/blob/main/docs/api.md) 

Ref [Pull a Model](https://github.com/jmorganca/ollama/blob/main/docs/api.md#pull-a-model)

The chart gonna be updated with the possibility to set a default model to serve at the startup.

**Comment by LarsAC** [comment]
Great for quick turnaround, that's very useful!
